#sudo: required

language: python

#os:
#  - linux
#  - osx

python:
  - "2.7"
  - "3.6"

# command to install dependencies
install:
  - pip --version
  - pip install -r travis_requirements.txt

# command to run tests
script:
  - tox